/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.prl;

import java.awt.BorderLayout;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.OutlineView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.util.lookup.ProxyLookup;
import org.openide.windows.WindowManager;
import systems.tech247.dbaccess.DataAccess;
import systems.tech247.hr.Employees;
import systems.tech247.hr.TblPeriods;
import systems.tech247.util.CapCreatable;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//systems.tech247.prl//EmployeePayrollCodes//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "EmployeePayrollCodesTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "systems.tech247.prl.EmployeePayrollCodesTopComponent")
//@ActionReference(path = "Menu/Window" /*, position = 333 */)
//@TopComponent.OpenActionRegistration(
//        displayName = "#CTL_EmployeePayrollCodesAction",
//        preferredID = "EmployeePayrollCodesTopComponent"
//)
@Messages({
    "CTL_EmployeePayrollCodesAction=Employee Payroll Codes",
    "CTL_EmployeePayrollCodesTopComponent= Payroll Codes",
    "HINT_EmployeePayrollCodesTopComponent= Payroll Codes"
})
public final class EmployeePayrollCodesTopComponent extends TopComponent implements ExplorerManager.Provider,LookupListener {

    Lookup.Result<TblPeriods> rslt = WindowManager.getDefault().findTopComponent("PeriodsTopComponent").getLookup().lookupResult(TblPeriods.class);
    ExplorerManager em = new ExplorerManager();
    Employees emp;
    InstanceContent content = new InstanceContent();
    TblPeriods period = DataAccess.getCurrentMonth();
    Lookup lookup = new AbstractLookup(content);
    public EmployeePayrollCodesTopComponent() {
        this(null);
    }
    public EmployeePayrollCodesTopComponent(final Employees emp) {
        initComponents();
        setName("Payroll Codes ->"+ emp.getSurName()+" "+emp.getOtherNames());
        setToolTipText(Bundle.HINT_EmployeePayrollCodesTopComponent());
        this.emp = emp;
        setLayout(new BorderLayout());
        OutlineView ov = new OutlineView("Code");
        
        ov.addPropertyColumn("amount", "Amount");
        ov.addPropertyColumn("active", "Active");
        ov.addPropertyColumn("deduction", "Deduction");
        ov.addPropertyColumn("currency", "Currency");
        ov.getOutline().setRootVisible(false);
        add(ov);
        //content.add();
        associateLookup(new ProxyLookup(lookup,ExplorerUtils.createLookup(em, getActionMap())));
        
        content.add(new CapCreatable() {
            @Override
            public void create() {
                TopComponent tc = new EmployeePayrollCodeEditorTopComponent(emp);
                tc.open();
                tc.requestActive();
            }
        });
        
        rslt.addLookupListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        reload();
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }

    @Override
    public void resultChanged(LookupEvent ev) {
        Lookup.Result<TblPeriods> rslt = (Lookup.Result<TblPeriods>)ev.getSource();
        for(TblPeriods p: rslt.allInstances()){
            period = p;
            reload();
        }
    }
    
    void reload(){
        em.setRootContext(new AbstractNode(Children.create(new FactoryEmployeePayrollCodes(emp,false), true)));
    }
    
    
    
    
    
    
}
