/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.prl;

import systems.tech247.hr.TblPeriods;

/**
 *
 * @author Admin
 */
public class PayrollReportsOptions extends javax.swing.JPanel {

    /**
     * Creates new form PayrollRunOptions
     */
    TblPeriods period;
    public PayrollReportsOptions(TblPeriods period) {
        initComponents();
        this.period = period;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrbAllEmployeesPayroll = new javax.swing.JRadioButton();
        jrbRunReport = new javax.swing.JRadioButton();
        jrbSendPaySlips = new javax.swing.JRadioButton();
        jrbClosePeriod = new javax.swing.JRadioButton();
        jrbSendManagementReports = new javax.swing.JRadioButton();

        buttonGroup1.add(jrbAllEmployeesPayroll);
        org.openide.awt.Mnemonics.setLocalizedText(jrbAllEmployeesPayroll, org.openide.util.NbBundle.getMessage(PayrollReportsOptions.class, "PayrollReportsOptions.jrbAllEmployeesPayroll.text")); // NOI18N
        jrbAllEmployeesPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAllEmployeesPayrollActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbRunReport);
        org.openide.awt.Mnemonics.setLocalizedText(jrbRunReport, org.openide.util.NbBundle.getMessage(PayrollReportsOptions.class, "PayrollReportsOptions.jrbRunReport.text")); // NOI18N

        buttonGroup1.add(jrbSendPaySlips);
        org.openide.awt.Mnemonics.setLocalizedText(jrbSendPaySlips, org.openide.util.NbBundle.getMessage(PayrollReportsOptions.class, "PayrollReportsOptions.jrbSendPaySlips.text")); // NOI18N

        buttonGroup1.add(jrbClosePeriod);
        org.openide.awt.Mnemonics.setLocalizedText(jrbClosePeriod, org.openide.util.NbBundle.getMessage(PayrollReportsOptions.class, "PayrollReportsOptions.jrbClosePeriod.text")); // NOI18N
        jrbClosePeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbClosePeriodActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbSendManagementReports);
        org.openide.awt.Mnemonics.setLocalizedText(jrbSendManagementReports, org.openide.util.NbBundle.getMessage(PayrollReportsOptions.class, "PayrollReportsOptions.jrbSendManagementReports.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbAllEmployeesPayroll)
                    .addComponent(jrbRunReport)
                    .addComponent(jrbSendPaySlips)
                    .addComponent(jrbClosePeriod)
                    .addComponent(jrbSendManagementReports))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbAllEmployeesPayroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbRunReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbSendPaySlips)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbClosePeriod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbSendManagementReports)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbAllEmployeesPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAllEmployeesPayrollActionPerformed
        UtilityPLR.actionMap.put("report", "allemployeespayroll");
    }//GEN-LAST:event_jrbAllEmployeesPayrollActionPerformed

    private void jrbClosePeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbClosePeriodActionPerformed
        UtilityPLR.actionMap.put("action", "closeperiod");
    }//GEN-LAST:event_jrbClosePeriodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jrbAllEmployeesPayroll;
    private javax.swing.JRadioButton jrbClosePeriod;
    private javax.swing.JRadioButton jrbRunReport;
    private javax.swing.JRadioButton jrbSendManagementReports;
    private javax.swing.JRadioButton jrbSendPaySlips;
    // End of variables declaration//GEN-END:variables
}
