/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.prl;

import systems.tech247.hr.TblPeriods;

/**
 *
 * @author Admin
 */
public class PayrollRunOptions extends javax.swing.JPanel {

    /**
     * Creates new form PayrollRunOptions
     */
    TblPeriods period;
    public PayrollRunOptions(TblPeriods period) {
        initComponents();
        this.period = period;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrbPostPayroll = new javax.swing.JRadioButton();
        jrbSendPaySlips = new javax.swing.JRadioButton();
        jrbSendManagementReports = new javax.swing.JRadioButton();

        buttonGroup1.add(jrbPostPayroll);
        org.openide.awt.Mnemonics.setLocalizedText(jrbPostPayroll, org.openide.util.NbBundle.getMessage(PayrollRunOptions.class, "PayrollRunOptions.jrbPostPayroll.text")); // NOI18N
        jrbPostPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPostPayrollActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbSendPaySlips);
        org.openide.awt.Mnemonics.setLocalizedText(jrbSendPaySlips, org.openide.util.NbBundle.getMessage(PayrollRunOptions.class, "PayrollRunOptions.jrbSendPaySlips.text")); // NOI18N

        buttonGroup1.add(jrbSendManagementReports);
        org.openide.awt.Mnemonics.setLocalizedText(jrbSendManagementReports, org.openide.util.NbBundle.getMessage(PayrollRunOptions.class, "PayrollRunOptions.jrbSendManagementReports.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbPostPayroll)
                    .addComponent(jrbSendPaySlips)
                    .addComponent(jrbSendManagementReports))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbPostPayroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbSendPaySlips)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbSendManagementReports)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbPostPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPostPayrollActionPerformed
        UtilityPLR.actionMap.put("action", "post");
    }//GEN-LAST:event_jrbPostPayrollActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jrbPostPayroll;
    private javax.swing.JRadioButton jrbSendManagementReports;
    private javax.swing.JRadioButton jrbSendPaySlips;
    // End of variables declaration//GEN-END:variables
}
