/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.prleditorpanels;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.persistence.EntityManager;
import javax.swing.JButton;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import systems.tech247.dbaccess.DataAccess;
import systems.tech247.hr.Employees;
import systems.tech247.hr.TblNSSF;
import systems.tech247.prl.PayrollCodeCover;
import systems.tech247.prl.PeriodCover;



/**
 *
 * @author Admin
 */
public class PLRNSSFPanel extends javax.swing.JPanel implements LookupListener{
    
  
    
    
    DataAccess da = new DataAccess();
    
    Employees e;
    String sqlString;
    String searchString;
    NumberFormat nf = new DecimalFormat("#,###.00");
    NumberFormat percentageFormat = new DecimalFormat("##.##%");
    
    EntityManager entityManager = DataAccess.getEntityManager();
    TopComponent payrollcodesTc = WindowManager.getDefault().findTopComponent("PayrollCodesTopComponent");
    Lookup.Result<PayrollCodeCover> pcodeRslt = payrollcodesTc.getLookup().lookupResult(PayrollCodeCover.class);
    
    TopComponent periodsTc = WindowManager.getDefault().findTopComponent("PeriodsTopComponent");
    Lookup.Result<PeriodCover> paidperiodsRslt = periodsTc.getLookup().lookupResult(PeriodCover.class);
    
    
    
    /**
     * Creates new form PersonalInfoPanel
     */
    public PLRNSSFPanel() {
        initComponents();
        //Start transaction
        TblNSSF nssf= DataAccess.getNSSF();
        
        jtCriteria.setText(nssf.getNSSFCriteriaPayrollCodeID().getPayrollCodeName());
        jtMaxContribution.setText(nf.format(nssf.getEmployeeMaximum()));
        jtPercentage.setText(percentageFormat.format(nssf.getBasicPercentage()));
        jtEmployerFactor.setText(percentageFormat.format(nssf.getEmployerFactor()/100));
        jtRounding.setText(nf.format(nssf.getNSSFRounding()));
        jcbDefinedContribution.setSelected(nssf.getDefineContribution());
        
        jtVoluntaryCode.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent e) {
               // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent e) {
                Object[] options = {new JButton("Close")};
                DialogDisplayer.getDefault().notify(new DialogDescriptor(payrollcodesTc, "Select A Payroll Code",true, options,null,DialogDescriptor.DEFAULT_ALIGN,null,null));
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
       
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        viewPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtCriteria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtVoluntaryCode = new javax.swing.JTextField();
        jtPercentage = new javax.swing.JFormattedTextField();
        jtMaxContribution = new javax.swing.JFormattedTextField();
        jtRounding = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jtEmployerFactor = new javax.swing.JFormattedTextField();
        jcbDefinedContribution = new javax.swing.JCheckBox();

        jTextField3.setText(org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jTextField3.text")); // NOI18N

        jTextField4.setText(org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jTextField4.text")); // NOI18N

        viewPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jLabel1.text")); // NOI18N

        jtCriteria.setBackground(new java.awt.Color(0, 204, 0));
        jtCriteria.setText(org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jtCriteria.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jLabel5.text")); // NOI18N

        jtVoluntaryCode.setBackground(new java.awt.Color(0, 204, 0));
        jtVoluntaryCode.setText(org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jtVoluntaryCode.text")); // NOI18N

        jtPercentage.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        jtPercentage.setText(org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jtPercentage.text")); // NOI18N

        jtMaxContribution.setText(org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jtMaxContribution.text")); // NOI18N

        jtRounding.setText(org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jtRounding.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jLabel6.text")); // NOI18N

        jtEmployerFactor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        jtEmployerFactor.setText(org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jtEmployerFactor.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jcbDefinedContribution, org.openide.util.NbBundle.getMessage(PLRNSSFPanel.class, "PLRNSSFPanel.jcbDefinedContribution.text")); // NOI18N
        jcbDefinedContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDefinedContributionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbDefinedContribution)
                    .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtCriteria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtVoluntaryCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtPercentage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtMaxContribution, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtRounding, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtEmployerFactor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtEmployerFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtMaxContribution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtRounding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbDefinedContribution)
                .addGap(7, 7, 7)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtVoluntaryCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbDefinedContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDefinedContributionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDefinedContributionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JCheckBox jcbDefinedContribution;
    private javax.swing.JTextField jtCriteria;
    private javax.swing.JFormattedTextField jtEmployerFactor;
    private javax.swing.JFormattedTextField jtMaxContribution;
    private javax.swing.JFormattedTextField jtPercentage;
    private javax.swing.JFormattedTextField jtRounding;
    private javax.swing.JTextField jtVoluntaryCode;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void resultChanged(LookupEvent ev) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

      
    

    
    

    
    
    
    
    
    
    
    
    
    
    
        
        
        
        
    

    
}
